# Generated by Django 4.2.4 on 2023-08-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='direccion',
            field=models.CharField(max_length=50, verbose_name='La direccion'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='tfno',
            field=models.CharField(max_length=7, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='entregado',
            field=models.BooleanField(verbose_name='Entregado?'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='numero',
            field=models.IntegerField(verbose_name='El numemro del pedido'),
        ),
    ]
